// paho-mqtt/src/event.rs
//
// This file is part of the Eclipse Paho MQTT Rust Client library.

/*******************************************************************************
 * Copyright (c) 2026 Frank Pagliughi <fpagliughi@mindspring.com>
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * and Eclipse Distribution License v1.0 which accompany this distribution.
 *
 * The Eclipse Public License is available at
 *    http://www.eclipse.org/legal/epl-v20.html
 * and the Eclipse Distribution License is available at
 *   http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *    Frank Pagliughi - initial implementation and documentation
 *******************************************************************************/

//! The events that can be generated by the MQTT client library.

use crate::{Message, Properties, ReasonCode};

/// Events emitted by the client.
pub enum Event {
    /// The connection was established/re-established.
    Connected,
    /// An incoming message from the broker.
    Message(Message),
    /// The connection was lost unexpectedly.
    ConnectionLost,
    /// Received a disconnect message from the broker.
    Disconnected {
        /// The message properties from the disconnect message.
        props: Properties,
        /// The reason code from the disconnect message.
        reason_code: ReasonCode,
    },
    /// When the consumer is being shut down (such as from another thread)
    Shutdown,
}
