name: Paho MQTT Rust

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt
      - run: cargo fmt --all --check

  check:
    name: Rust Build Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
          - 1.75.0
    steps:
      - uses: actions/checkout@v6
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Resolve dependencies for MSRV
        run: |
          mkdir -p $HOME/.cargo
          echo 'resolver.incompatible-rust-versions = "fallback"' > $HOME/.cargo/config.toml
          cargo +stable update

      - name: Build check
        run: cargo check --all-targets

  clippy:
    name: Rust Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.75.0
          override: true
          components: clippy

      - name: Resolve dependencies for MSRV
        run: |
          mkdir -p $HOME/.cargo
          echo 'resolver.incompatible-rust-versions = "fallback"' > $HOME/.cargo/config.toml
          cargo +stable update

      - name: Clippy lints
        run: cargo +1.75.0 clippy --no-deps --all-targets -- -D warnings

  test:
    name: Rust Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
          - 1.75.0
    steps:
      - uses: actions/checkout@v6
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Resolve dependencies for MSRV
        run: |
          mkdir -p $HOME/.cargo
          echo 'resolver.incompatible-rust-versions = "fallback"' > $HOME/.cargo/config.toml
          cargo +stable update

      - name: Run tests
        run: cargo test --no-default-features --features bundled,vendored-ssl --no-fail-fast

